line-length = 120
target-version = "py37"

[lint]
select = [
    "E",
    "W",
    "F",
    "I",
    "UP",
]
ignore = []
per-file-ignores = { "__init__.py" = ["F401"] }

[format]
docstring-code-format = true
docstring-code-line-length = "dynamic"
quote-style = "double"
skip-magic-trailing-comma = false
